pipeline {
    agent any
    environment {
        DOCKERFILE_POSTGRES= 'Dockerfile_postgres'       // Nome do Dockerfile para a imagem db
        DOCKE_COMPOSE = 'docker-compose.yml'         // Nome do Docker-compose para a construção das demais imagens
        
    }
    stages {

        stage('Build Images') {
            steps {
                script {
                    // Nome das imagens
                    def imageNameWeb = 'rogerramossilva/web'
                    def imageNameDB = 'rogerramossilva/db'
                    def imageNameNginx = 'rogerramossilva/nginx'

                    // Executa o build das imagens com os respectivos Dockerfiles
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhubrogerio') {
                        def webImage = docker.build("${imageNameWeb}:${DOCKER_IMAGE_TAG}", "-f ${DOCKERFILE_WEB} .")
                        def dbImage = docker.build("${imageNameDB}:${DOCKER_IMAGE_TAG}", "-f ${DOCKERFILE_DB} .")
                        def nginxImage = docker.build("${imageNameNginx}:${DOCKER_IMAGE_TAG}", "-f ${DOCKERFILE_NGINX} .")

                        webImage.push()
                        dbImage.push()
                        nginxImage.push()
                    }
                }
            }
        }
        stage('Teste Aplicação') {
            steps {
                // Testes automatizados da aplicação
                sh 'docker-compose -f docker-compose.yml up -d'

                // Realize os testes nos serviços em execução
                // Exemplo de teste usando curl para verificar se o serviço web está respondendo
                sh 'curl -I http://localhost'

                sh 'docker-compose -f docker-compose.yml down'
            }
        }
        stage('Aprovação') {
            steps {
                input 'Deseja prosseguir com o Deploy e Push?'
            }
        }

 }
}
